### PR TITLE
Add Clone support

### PR DESCRIPTION
**Pull request by ocornoc**
Had a use for `Clone` support, so here it is. Made sure to do it across features, too.

### CODE REVIEW

**Comment by shnarazk** [comment]
Hi, I have no objection to adding `Clone.` But you also add `Copy` to some structs. Do you need it really? Actually, I don't like to adopt copy semantics on structs.

**Comment by ocornoc** [comment]
Not adopting `Copy` where possible in a library is a problem: while you may disagree with it, you've now forced the rest of your users down the line not to be able to use the full extent of Rust too.

I'm happy to remove it, but going out of my way to restrict libraries users for ideological purposes seems unfortunate.

**Comment by shnarazk** [comment]
Hmm, I can accept `Copy` trait on `CertificatedRecord`. But I want to keep move semantics on the rest, namely`Var`, `Progress.*`, `LubySeries`, `ProgressRecord` and `Ema.*` to avoid my careless mistakes.
Please just call `clone` method explicitly if you need a copy. Isn't it enough?

**Comment by ocornoc** [comment]
Alright. I'll be able to update the PR in roughly 8-10 hours.

**Comment by shnarazk** [comment]
Thank you very much! I'll merge it into the upcoming 0.6.3.

**Comment by shnarazk** [comment]
Since the diff is simple, I already committed it on branch dev-0.6.3 by myself b1f822ff368b1325391e441023dbee32698c71b2. Thank anyway.

**Comment by ocornoc** [comment]
I forgot, lol thanks.

**Pull request closed without merging**
